version: '3'
services:
   web:
     image: nginx
     ports:
       - "80"
     volumes:
       - /root/myweb/:/usr/share/nginx/html
   app:
     image: tomcat
     ports:
       - "8080"
   db:
     image: redis
     ports:
        - "9080"
